### PR TITLE
Fixed stop timer bug. Closes #73.

### LINKED ISSUE #73: Error when using server.stop() and good-file
Hello guys, here is the error when I call server.stop() having registered good-file plugin:
```
/my_project/node_modules/good-file/node_modules/big-time/lib/index.js:64
  return timer.close();
              ^

TypeError: Cannot read property 'close' of null
    at Object._clearTimeout [as clearTimeout] (/my_project/node_modules/good-file/node_modules/big-time/lib/index.js:64:15)
    at null.<anonymous> (/my_project/node_modules/good-file/lib/index.js:146:12)
    at emitNone (events.js:67:13)
    at emit (events.js:166:7)
    at internals.Monitor.stop (/my_project/node_modules/good/lib/monitor.js:220:10)
    at null.<anonymous> (/my_project/node_modules/good/lib/index.js:14:17)
    at emitNone (events.js:67:13)
    at emit (events.js:166:7)
    at EventEmitter.handler (/my_project/node_modules/hapi/node_modules/kilt/lib/index.js:56:44)
    at emitNone (events.js:67:13)
```
You can test it yourself with:
```javascript
var Hapi = require('hapi'),
    serverStopped = false;

var server = new Hapi.Server({ debug: { request: ['error'] } });

server.connection({ port: 1234 });

var stopGracefully = function(code){

  if(serverStopped) return;
  
  console.log('stopping server gracefully...');

  serverStopped = true;

  server.stop({timeout: 30000}, function(){
    console.log('all connections closed.');
    process.exit(code);
  });
};


// HANDLE KILL EVENTS

process.on("uncaughtException", function(err) {
  console.error(err);
  return stopGracefully(1); // 1 : failure
});
 
process.on("SIGTERM", function() {
  return stopGracefully(0);
});
 
process.on("SIGINT", function() {
  return stopGracefully(0);
});


server.register({
  register: require('good'),
  options: {
    reporters: [{
      reporter: require('good-console'),
      events: {
        response: '*',
        log: '*',
        error: '*' 
      }
    },
    {
      reporter: require('good-file'),
      config: './api.log',
      events: {
        log: '*',
        error: '*'
      }
    }]
  }
}, function (error) { 
  if(error) console.error(error);

  server.start(function () {
    server.log('info', 'Server running');

    setTimeout(function(){
      stopGracefully();
    }, 3000)
  });
});
```

Any idea please?

### PR DESCRIPTION
**Pull request by arb**

### CODE REVIEW

File: test/index.js [hunk 1]
```diff
@@ -119,6 +120,46 @@ describe('GoodFile', function () {
...
+
+            ee.emit('stop');
+
+            reporter._streams.write.on('finish', function () {
+
+                expect(reporter._streams.write.bytesWritten).to.equal(53);
+                expect(reporter._streams.write._writableState.ended).to.be.true();
+
+                internals.removeLog(reporter._streams.write.path);
+                Bt.clearTimeout = clear;
```
Comment (cjihrig) [inline test/index.js]: If possible, this should be restored before any assertions are made. Otherwise, `clearTimeout()` will be borked for later tests.

**Comment by arb** [comment]
@cjihrig I moved it up as high as it can go and still be an effective test.
